//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexis.WindowsPhone.Social.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alexis.WindowsPhone.Social.Resources.LangResource", typeof(LangResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 绑定豆瓣网 的本地化字符串。
        /// </summary>
        public static string BindDouban {
            get {
                return ResourceManager.GetString("BindDouban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已绑定 的本地化字符串。
        /// </summary>
        public static string Binded {
            get {
                return ResourceManager.GetString("Binded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定人人网 的本地化字符串。
        /// </summary>
        public static string BindRenren {
            get {
                return ResourceManager.GetString("BindRenren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定腾讯微博 的本地化字符串。
        /// </summary>
        public static string BindTencent {
            get {
                return ResourceManager.GetString("BindTencent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定新浪微博 的本地化字符串。
        /// </summary>
        public static string BindWeibo {
            get {
                return ResourceManager.GetString("BindWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分享到 的本地化字符串。
        /// </summary>
        public static string ShareTo {
            get {
                return ResourceManager.GetString("ShareTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除绑定 的本地化字符串。
        /// </summary>
        public static string UnBind {
            get {
                return ResourceManager.GetString("UnBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未绑定 的本地化字符串。
        /// </summary>
        public static string UnBinded {
            get {
                return ResourceManager.GetString("UnBinded", resourceCulture);
            }
        }
    }
}
